### ISSUE TITLE
Unsupported environment error

### ISSUE THREAD

**Issue by suraj-dot-gupta** [junkurihara/jscu#1138]
Hi @junkurihara , while running the code locally it works fine.
But while using in aws with centos os getting below error,

```
core.mjs:6469 ERROR Error: Uncaught (in promise): Error: UnsupportedEnvironment
Error: UnsupportedEnvironment
    at eval (aes.js:159:23)
    at step (aes.js:55:23)
    at Object.eval [as next] (aes.js:36:53)
    at eval (aes.js:30:71)
    at new ZoneAwarePromise (zone.js:1340:1)
    at __awaiter (aes.js:26:12)
    at Object.decrypt (aes.js:142:12)
    at _callee2$ (rum.js:99:77)
    at tryCatch (runtime.js:63:40)
    at Generator.invoke [as _invoke] (runtime.js:293:22)
    at resolvePromise (zone.js:1255:1)
    at zone.js:1162:1
    at asyncGeneratorStep (asyncToGenerator.js:10:5)
    at _throw (asyncToGenerator.js:33:9)
    at ZoneDelegate.invoke (zone.js:400:1)
    at Object.onInvoke (core.mjs:25450:1)
    at ZoneDelegate.invoke (zone.js:399:1)
    at Zone.run (zone.js:160:1)
    at zone.js:1318:1
```

Thanks!

**Comment by junkurihara** [comment]
Hello @suraj-dot-gupta 

Please let me show your code and environment like Node.js version, framework, lambda or ec2 or lightsail, etc etc.
Honestly, I am not sure if I can provide a solution for this without access to actual environment....

**Comment by suraj-dot-gupta** [comment]
Hi @junkurihara , i found the issue , since the server was running on http, it was throwing that error.
Thanks!!

**Comment by junkurihara** [comment]
I think in the environment of `http`, Node.js crypto module cannot be called much like webcrypto on browsers....
